[build]
  command = "npm run build"
  publish = "frontend/out"

[build.environment]
  NODE_VERSION = "20"
  NETLIFY_SKIP_NEXTJS_PLUGIN = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    disable = true
